### ISSUE TITLE
Enviar pelo WhatsApp ou Telegram

### ISSUE THREAD

**Issue by grupoquarentena** [grupoquarentena/resumoDaAta#9]

**Comment by cirinho** [comment]
Melhor pelo telegram, pois já existe API própria simplificada com bot usando a biblioteca UrlFetchApp.

Pelo whatsapp teria que rodar uma API própria tipo wppconnect e com o meu número do whatsapp.

**Comment by cirinho** [comment]
> Pelo whatsapp teria que rodar uma API própria tipo wppconnect e com o meu número do whatsapp.

https://wppconnect.io

https://github.com/wppconnect-team

**Comment by cirinho** [comment]
Utilizado o EvolutionAPI para enviar mensagem pelo WhatsApp
